### ISSUE TITLE
fabric wont start 

### ISSUE THREAD

**Issue by Ilupo4399** [Ilupo4399/k2view---fabric---linux#1]
ERROR 2022-04-14 17:08:34,364 [LIDc0c000000000001] [main] c.k.f.b.Boot -
java.lang.ExceptionInInitializerError: null
at com.k2view.cdbms.boot.FabricSystemSchemaCreate.loadDAOs(FabricSystemSchemaCreate.java:81)
at com.k2view.cdbms.boot.FabricSystemSchemaCreate.start(FabricSystemSchemaCreate.java:34)
at com.k2view.fabric.boot.BootContext.start(BootContext.java:89)
at com.k2view.fabric.boot.BootContext.start(BootContext.java:72)
at com.k2view.fabric.boot.BootContext.start(BootContext.java:57)
at com.k2view.fabric.boot.Boot.start(Boot.java:70)
at com.k2view.fabric.boot.Boot.main(Boot.java:108)

**Comment by Ilupo4399** [comment]
![image](https://user-images.githubusercontent.com/99248884/163457680-28fe65ec-a215-4d05-b11b-b91d6a84bd1a.png)
